config/routes.rb
Rails.application.routes.draw do
  Rails.application.routes.default_url_options[:host] = "XXX"
  get 'signout', to: 'sessions#destroy', as: 'signout'

  devise_for :users

  resources :users, only: [:index, :show]
  resources :friend_requests, only: [:create, :destroy]
  resources :friendships, only: [:create, :destroy]
  resources :likes, only: [:create, :destroy]
  resources :posts
  resources :comments


  root to: 'posts#index'


  get 'likes', to: 'posts#index'
  post 'posts/:id/edit', to: 'posts#update'

  post 'posts/new',    to: 'posts#create'
  post 'comments/new', to: 'comments#create'
  post 'users/:id',    to: 'posts#create'

  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
 

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :friendships, dependent: :destroy
  has_many :friends, through: :friendships

  has_many :posts, dependent: :destroy

  has_many :received_friend_requests, 
            class_name: 'FriendRequest', 
            foreign_key: :requestee_id,
            dependent: :destroy

  has_many :sent_friend_requests, 
            class_name: 'FriendRequest', 
            foreign_key: :requester_id,
            dependent: :destroy

  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy


  after_create :send_welcome_email

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0, 20]
      user.name = auth.info.name
    end
  end

  def send_welcome_email
    UserMailer.welcome_email(self).deliver_now
    #UserMailer.with(user: @user).welcome_email.deliver_now
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :authenticate_user!
    
    def index
      @users = User.all
      @users = @users - [current_user]
      @all_friends = current_user.friends.all
    end
  
    def show
      @user = User.find(params[:id])
      @all_users = User.all
      @friends = current_user.friends.all
      @posts = Post.includes(:user).where(user_id: @user.id).order(created_at: :desc )
    end
  end

app/helpers/users_helper.rb
module UsersHelper
    def friends
      current_user.friends.all
    end
    
    def find_request(user)
      FriendRequest.where('requester_id = ? AND
                     requestee_id = ?',
                      user.id, current_user.id)[0]
    end
  
    def sent_requests
      requests = FriendRequest.includes(:requestee).where('requester_id = ?',
                                     current_user.id)
      return [-1] if requests.nil?
      requests = requests.map { |r| r.requestee }
      requests
    end
  
    def received_requests
      requests = FriendRequest.includes(:requester).where('requestee_id = ?',
                                     current_user.id)
      return [-1] if requests.nil?
      requests = requests.map { |r| r.requester }
      requests
    end
  
    def friend_request_list
      requests = FriendRequest.includes(:requester).where(requestee_id: current_user.id).limit(5)
      requests
    end
  end

app/views/users/index.html.erb
<div class="row">
  <div class="col-10 col-md-8 col-lg-5 col-xl-4 mt-4">
    <% @users.each do |user| %>
      <div class="d-flex align-items-center justify-content-between">
        <%= link_to user.name, user_path(user.id), class: "name-link post-author overflow-wrap" %>

        <% if current_user.friends.include?(user) %>
        <%= link_to 'unfriend', friendship_path(user.id), method: 'delete', class: "stop-btn" %>
        <% elsif sent_requests.include?(user) %>      
            <p>Friend request sent</p>
        <% else %>
            <p>send friend request</p>
        <% end %>


        <% if received_requests.include?(user) %>
        <p>accept friendship</p>
          <div class="d-flex">
            <%= link_to 'Accept', friendships_path(friend_request: find_request(user)),method: 'post', class: "go-btn mx-3" %>
            <%= link_to 'Deny', friend_request_path(find_request(user)), method: 'delete', class: "stop-btn" %>
        </div>
        <% elsif !current_user.friends.include?(user) %>
        <%= button_to 'Send Request', friend_requests_path(user_id: user.id), method: 'post', class: "go-btn my-3" %>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class="row">
  <div class="col-12 col-xl-4 my-2 my-xl-4 d-flex flex-column align-items-center d-lg-block">
    <h1 class="mx-4"><%= @user.name %></h1>
  </div>

  <div class="col-12 col-xl-5 mt-4 d-flex flex-column align-items-center d-lg-block">
    <div class="w-100">  
      <% if current_user == @user %>
        <div class="mt-3"><%= render 'posts/new_post' %></div>
      <% end %>
      <% if (current_user == @user) || (@friends.include? @user) %>
      <% if @posts.any? %>
        <% @posts.each do |p| %>
          <div class="my-2 py-2 px-3">
            <div class="d-flex">
              <% if current_user == p.user %>
                <div class="align-self-end mb-1">
                  <%= link_to 'edit', edit_post_path(p.id), class: "mx-1" %>
                  <%= link_to 'delete', post_path(p.id), method: :delete %>
                </div>
              <% end %>
            </div>
            <div class="d-flex justify-content-between">
              <div class="text-break">
                <%= p.body %>
              </div>
            </div>
            <div class="mb-4">
            <p class="like-count d-inline mr-1 text-muted"><%= p.likes.size %>
              <% if already_liked?(p) %>
                <u><%= link_to 'unmeh', like_path(current_like(p).id), method: 'delete', class: "meh" %></u>
              <% else %>
                <u><%= link_to "meh", likes_path(post: p), method: 'post', class: "meh" %></u>
              <% end %>
            </div>
            <% if p.comments.any?%>
              
                <% p.comments.each do |c| %>
                  <div class="d-flex align-items-center">
                    <div class="d-flex flex-column">
                      <%= link_to c.user.name, user_path(c.user.id), class: "name-link comment-author overflow-wrap" %>
                    </div>
                  </div>
                  <div class="d-flex comment-box">
                    <div class="pr-2 mb-2 comment"><%= c.body %></div>
                    <% if c.user == current_user %>
                      <%= link_to 'delete', comment_path(c), method: 'delete' %>
                    <% end %>
                  </div>
                <% end %>
            <% end %>
            <hr>
            <div class="form-group">
              <%= form_for :comment, url: new_comment_path(p.id) do |f| %>
                <%= f.hidden_field :post_id, value: p.id %>
                <%= f.text_area :body, placeholder: 'Now what?', class: 'form-control' %>
                <%= f.submit 'Comment', class: "go-btn" %>
              <% end %>
            </div>
          </div>
        <% end %>
      <% end %>
      <% else %>
       <h3>You must be friends to see their posts.</h3>
      <% end %>
    </div>
  </div>

  <div class="col-9 col-md-6 col-lg-4 col-xl-3 mt-xl-4">
    <% if @user == current_user %>
    <h3>Friend requests:</h3>
    <% if friend_request_list.empty? %>
        <p>no friend request</p>
    <% else %>
        <% friend_request_list.each do |r| %>
        <div class="d-flex align-items-center">
            <%= link_to r.name, user_path(r.id), class: "name-link post-author overflow-wrap" %>
              <div class="d-flex">
                <%= button_to 'Accept', friendships_path(friend_request: request), class: "go-btn mx-3" %>
                <%= button_to 'Deny', friend_request_path(request.id), method: 'delete', class: "stop-btn" %>
            </div>
        </div>
        <% end %>
    <% end %>
    <% end %>
    <% if friends.include?(@user) %>

    <%= button_to 'Forget this fool', friendship_path(@user), method: 'delete', class: "stop-btn" %>
    <% elsif sent_requests.include?(@user) %>
    <% if %> 
        <p>Friend request sent</p>
    <% else %>
        <p>send friend request
    <% end %>
    <% elsif received_requests.include?(@user) %>

    <%= render 'request', { request: find_request(@user) } %>
    <% elsif @user != current_user %>

    <%= button_to 'Send Request', friend_requests_path(user_id: user.id, path: path), class: "go-btn my-3" %>
    <% end %>
    <%= link_to 'Search for friends (good luck)', users_path %>
  </div>
</div>