config/routes.rb
Rails.application.routes.draw do
  Rails.application.routes.default_url_options[:host] = "XXX"
  get 'signout', to: 'sessions#destroy', as: 'signout'

  devise_for :users

  resources :users, only: [:index, :show]
  resources :friend_requests, only: [:create, :destroy]
  resources :friendships, only: [:create, :destroy]
  resources :likes, only: [:create, :destroy]
  resources :posts
  resources :comments


  root to: 'posts#index'


  get 'likes', to: 'posts#index'
  post 'posts/:id/edit', to: 'posts#update'

  post 'posts/new',    to: 'posts#create'
  post 'comments/new', to: 'comments#create'
  post 'users/:id',    to: 'posts#create'

  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
 

end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!

  def index
    @friends = current_user.friends.all
    @friends_list = @friends.limit(10)
    @posts = Post.where(user_id: current_user.friends).or(Post.where(user_id: current_user)).order(created_at: :desc).limit(10)
  end

  def new
    @post = Post.new
  end

  def create
    @post = current_user.posts.build(post_params)
    if @post.save
      redirect_to request.referrer
    else
      render :new
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to request.referrer
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    @post.update(post_params)
    redirect_to user_path(current_user)
  end
  
  private

  def post_params
    params.require(:post).permit(:body)
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_with(model: post) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>


  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/_new_post.html.erb
<div class="field form-group mb-4 d-flex flex-column position-relative mb-5 new-post">
  <%= form_for :post, url: new_post_path(current_user.id)do |f| %>
    <%= f.text_area :body, placeholder: "What is so important?", class: "form-control" %><br /> 
    <div class="d-flex justify-content-end">
    <%= f.submit 'Share with the world', class: "go-btn" %>
    </div>
  <% end %>
</div>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>
<div class="row">
  <div class="col-12 col-xl-3 my-2 my-xl-4 d-flex flex-column align-items-center d-lg-block">
  <% if user_signed_in? %>
  <h1 class="mx-4"><%= current_user.name %></h1>
    <%= link_to 'Edit', edit_user_registration_path(current_user), class: "edit-profile" %>
  <% end %> 
  </div>

  <div class="col-12 col-xl-6 mt-4 d-flex flex-column align-items-center d-lg-block">
    <div class="w-100">
      <div class="mt-3"><%= render 'new_post' %></div>
      <% if @posts.any? %>
        <% @posts.each do |p| %>
          <div class="my-2 py-2 px-3">
            <div class="d-flex">
              <% if current_user == p.user %>
                <div class="align-self-end mb-1">
                  <%= link_to 'edit', edit_post_path(p.id), class: "mx-1" %>
                  <%= link_to 'delete', post_path(p.id), method: :delete %>
                </div>
              <% end %>
            </div>
            <div class="d-flex justify-content-between">
              <div class="text-break">
                <%= p.body %>
              </div>
            </div>
            <div class="mb-4">
            <p class="like-count d-inline mr-1 text-muted"><%= p.likes.size %>
              <% if already_liked?(p) %>
                <u><%= link_to 'unlike', like_path(current_like(p).id), method: 'delete'%></u>
              <% else %>
                <u><%= link_to "like", likes_path(post: p), method: 'post'%></u>
              <% end %>
            </div>
            <% if p.comments.any?%>
              
                <% p.comments.each do |c| %>
                  <div class="d-flex align-items-center">
                    <div class="d-flex flex-column">
                      <%= link_to c.user.name, user_path(c.user.id), class: "name-link comment-author overflow-wrap" %>
                    </div>
                  </div>
                  <div class="d-flex comment-box">
                    <div class="pr-2 mb-2 comment"><%= c.body %></div>
                    <% if c.user == current_user %>
                      <%= link_to 'delete', comment_path(c), method: 'delete' %>
                    <% end %>
                  </div>
                <% end %>
            <% end %>
            <hr>
            <div class="form-group">
              <%= form_for :comment, url: new_comment_path(p.id) do |f| %>
                <%= f.hidden_field :post_id, value: p.id %>
                <%= f.text_area :body, placeholder: 'Now what?', class: 'form-control' %>
                <%= f.submit 'Comment', class: "go-btn" %>
              <% end %>
            </div>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
  <div class="col-12 col-xl-3 mt-xl-4">
    <h3>Your Friends:</h3>
    <% if @friends_list.any? %>
      <% @friends_list.each do |f| %>
        <div class="d-flex align-items-center">
          <div class="d-flex flex-column">
            <%= link_to f.name, user_path(f.id), class: "name-link post-author overflow-wrap" %>
          </div>
        </div>
      <% end %>
<% end %>
  <hr>
      <%= link_to "Find a friend", users_path %>
    

  </div>
</div>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Body:</strong>
  <%= @post.body %>
</p>

<p>
  <strong>User:</strong>
  <%= @post.user_id %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>